<?php

// hook permision

function cronmonitor_permission() {
  return array(
    'administer cronmonitor' => array(
      'title' => t('Administer Cron Monitor'),
      'description' => t('Perform administration tasks for Cron Monitor'),
    ),
  );
}


// Implement hook menu

  function cronmonitor_menu() {
    $items['admin/config/cronmonitor'] = array(
	'title' => 'Cron Monitor Settings',
	'type' => MENU_NORMAL_ITEM,
	'page callback' => 'drupal_get_form',
	'page arguments' => array('cronmonitor_admin_form'),
	'access arguments' => array('administer cronmonitor')
	  // Page callback, etc. need to be added here.
	);
    return $items;
  }

  // form for cron monitor



function cronmonitor_admin_form($form, &$form_state) {

	$form['cronmonitor_enable'] = array(
		'#type' =>'checkbox', 
		'#title' => t('Enable Cron Monitor'),
		'#default_value' => variable_get('cronmonitor_enable', 0)
	);

	$form['cronmonitor_email_text'] = array(
		'#title' => t('Text tp semd woth Cron Monitor'),
		'#type' => 'textarea',
		'#description' => t('Enter some text to send with the C M emails'),
		'#default_value' => variable_get('cronmonitor_email_text', '')
	);

  	return system_settings_form($form);
 }

 // implment hook_cron

function cronmonitor_cron() {
	if (variable_get('cronmonitor_enable', 0)) {
		//send cronmonitor email
		drupal_mail('cronmonitor','cronmonitor_email', 'jarimado@gmail.com', language_default());
	}
}

// implement hook mail

function cronmonitor_mail($key, &$message, $params) {
	switch($key) {
		case 'cronmonitor_email':
			$message['subject'] = t('this is a cron monitor report');
			$message['body'][] = t('this is a report from the cron mmonitor on @site-name', array('@site-name' => variable_get('site_name', 'junesitetest.yeahnah.tv')));
			$message['body'][] = t(variable_get('cronmonitor_email_text', ''));
			break;
	}
}




















